### ISSUE TITLE
DataLossError...............!

### ISSUE THREAD

**Issue by veeraharin** [AhmetHamzaEmra/Intelegent_Lock#3]
hi, 
I am getting the following error when i run "python3 main_code.py"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tflearn/initializations.py:119: UniformUnitScaling.__init__ (from tensorflow.python.ops.init_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
2018-01-23 20:01:46.705732: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
path ./model/my_model.tflearn
2018-01-23 20:01:48.172555: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 1023142078 vs. calculated on the restored bytes 662328829
2018-01-23 20:01:48.174926: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 91664377 vs. calculated on the restored bytes 1572371477
2018-01-23 20:01:48.175126: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 3562051217 vs. calculated on the restored bytes 1436366305
2018-01-23 20:01:48.175151: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 2743233166 vs. calculated on the restored bytes 3423742601
2018-01-23 20:01:48.175129: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 511452201 vs. calculated on the restored bytes 1214729159
2018-01-23 20:01:48.176313: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 91664377 vs. calculated on the restored bytes 1572371477
2018-01-23 20:01:48.176791: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 3162266982 vs. calculated on the restored bytes 2890847604
2018-01-23 20:01:48.177508: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 3363158527 vs. calculated on the restored bytes 2356514541
2018-01-23 20:01:48.177826: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 2315723916 vs. calculated on the restored bytes 2015907768
2018-01-23 20:01:48.177916: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 314258516 vs. calculated on the restored bytes 3942222521
2018-01-23 20:01:48.177982: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 188339952 vs. calculated on the restored bytes 1017069575
2018-01-23 20:01:48.178938: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 66084754 vs. calculated on the restored bytes 2795228591
2018-01-23 20:01:48.179333: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 141094046 vs. calculated on the restored bytes 3595362799
2018-01-23 20:01:48.180934: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 1392521279 vs. calculated on the restored bytes 322347086
2018-01-23 20:01:48.181136: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 1630541749 vs. calculated on the restored bytes 1040120677
2018-01-23 20:01:48.181926: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 3645530385 vs. calculated on the restored bytes 3707079508
2018-01-23 20:01:48.182506: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 3496139171 vs. calculated on the restored bytes 2262869991
2018-01-23 20:01:48.182594: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 3388135107 vs. calculated on the restored bytes 3397996067
2018-01-23 20:01:48.183270: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 717201017 vs. calculated on the restored bytes 715239342
2018-01-23 20:01:48.183758: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 191385343 vs. calculated on the restored bytes 31375631
2018-01-23 20:01:48.184008: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 1422169722 vs. calculated on the restored bytes 3952386992
2018-01-23 20:01:48.184868: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 3232978774 vs. calculated on the restored bytes 3357983005
2018-01-23 20:01:48.186157: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 3023058454 vs. calculated on the restored bytes 3508275387
2018-01-23 20:01:48.187281: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 169337673 vs. calculated on the restored bytes 1684377793
2018-01-23 20:01:48.187666: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 3486943653 vs. calculated on the restored bytes 4173295646
2018-01-23 20:01:48.188954: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 3862857029 vs. calculated on the restored bytes 2054704094
2018-01-23 20:01:48.189544: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 3041038455 vs. calculated on the restored bytes 1001679085
2018-01-23 20:01:48.190107: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 2460926327 vs. calculated on the restored bytes 4148356436
2018-01-23 20:01:48.192712: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 411918014 vs. calculated on the restored bytes 2088034305
2018-01-23 20:01:48.193644: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 2789654764 vs. calculated on the restored bytes 1471532794
2018-01-23 20:01:48.194545: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 2360534724 vs. calculated on the restored bytes 3916115864
2018-01-23 20:01:48.197834: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 4259864811 vs. calculated on the restored bytes 3296806277
2018-01-23 20:01:48.198637: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 4094537850 vs. calculated on the restored bytes 1570163143
2018-01-23 20:01:48.199320: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 2037083310 vs. calculated on the restored bytes 2531465183
2018-01-23 20:01:49.684359: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 519988316 vs. calculated on the restored bytes 349520506
2018-01-23 20:01:49.720522: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 2959698197 vs. calculated on the restored bytes 1805099933
2018-01-23 20:01:49.743673: W tensorflow/core/framework/op_kernel.cc:1192] Data loss: Checksum does not match: stored 2749618925 vs. calculated on the restored bytes 129760129
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: Checksum does not match: stored 1023142078 vs. calculated on the restored bytes 662328829
	 [[Node: save_1/RestoreV2_38 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_38/tensor_names, save_1/RestoreV2_38/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_code.py", line 29, in <module>
    model.load(path)
  File "/usr/local/lib/python3.5/dist-packages/tflearn/models/dnn.py", line 308, in load
    self.trainer.restore(model_file, weights_only, **optargs)
  File "/usr/local/lib/python3.5/dist-packages/tflearn/helpers/trainer.py", line 490, in restore
    self.restorer.restore(self.session, model_file)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Checksum does not match: stored 1023142078 vs. calculated on the restored bytes 662328829
	 [[Node: save_1/RestoreV2_38 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_38/tensor_names, save_1/RestoreV2_38/shape_and_slices)]]

Caused by op 'save_1/RestoreV2_38', defined at:
  File "main_code.py", line 25, in <module>
    model = tflearn.DNN(network, tensorboard_verbose=0)
  File "/usr/local/lib/python3.5/dist-packages/tflearn/models/dnn.py", line 65, in __init__
    best_val_accuracy=best_val_accuracy)
  File "/usr/local/lib/python3.5/dist-packages/tflearn/helpers/trainer.py", line 147, in __init__
    allow_empty=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

DataLossError (see above for traceback): Checksum does not match: stored 1023142078 vs. calculated on the restored bytes 662328829
	 [[Node: save_1/RestoreV2_38 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_38/tensor_names, save_1/RestoreV2_38/shape_and_slices)]]

*********** please tell me what does it mean.
thank you.

**Comment by AhmetHamzaEmra** [comment]
Sorry for inconvenience, the pre-trained model was missing some parts. current state is working fine. 

Thanks

**Comment by veeraharin** [comment]
thank you AhmetHamzaEmra its working fine
